version: "3"

services:
    bunseki:
        image: kaggle_cpu:v01
        build:
            context: .
            dockerfile: kaggle.dockerfile
#        volumes: 
#            - ${PWD}:/work
        ports:
            - 8181:8181
            - 8786:8786
            - 6006:6006 
        command: "jupyter lab --port 8181 --ip=0.0.0.0 --allow-root --LabApp.token=''"
        container_name: bun_cpu
        restart: always